
// This file has been generated by the GUI designer. Do not modify.
namespace GtkArchivos
{
	public partial class Win_Tel
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action InsertarDatosAction;
		
		private global::Gtk.Action VerDatosAction;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table7;
		
		private global::Gtk.Entry entry12;
		
		private global::Gtk.Entry entry13;
		
		private global::Gtk.Entry entry14;
		
		private global::Gtk.Entry entry15;
		
		private global::Gtk.Entry entry16;
		
		private global::Gtk.FileChooserButton filechooserbutton3;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.Button button7;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Button button5;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview2;
		
		private global::Gtk.Label GtkLabel6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkArchivos.Win_Tel
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.InsertarDatosAction = new global::Gtk.Action ("InsertarDatosAction", global::Mono.Unix.Catalog.GetString ("Insertar Datos"), null, null);
			this.InsertarDatosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Insertar Datos");
			w1.Add (this.InsertarDatosAction, null);
			this.VerDatosAction = new global::Gtk.Action ("VerDatosAction", global::Mono.Unix.Catalog.GetString ("Ver Datos"), null, null);
			this.VerDatosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ver Datos");
			w1.Add (this.VerDatosAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "GtkArchivos.Win_Tel";
			this.Title = global::Mono.Unix.Catalog.GetString ("Win_Tel");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GtkArchivos.Win_Tel.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table7 = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.entry12 = new global::Gtk.Entry ();
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '●';
			this.table7.Add (this.entry12);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry12]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entry13 = new global::Gtk.Entry ();
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '●';
			this.table7.Add (this.entry13);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry13]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entry14 = new global::Gtk.Entry ();
			this.entry14.CanFocus = true;
			this.entry14.Name = "entry14";
			this.entry14.IsEditable = true;
			this.entry14.InvisibleChar = '●';
			this.table7.Add (this.entry14);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry14]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entry15 = new global::Gtk.Entry ();
			this.entry15.CanFocus = true;
			this.entry15.Name = "entry15";
			this.entry15.IsEditable = true;
			this.entry15.InvisibleChar = '●';
			this.table7.Add (this.entry15);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry15]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entry16 = new global::Gtk.Entry ();
			this.entry16.CanFocus = true;
			this.entry16.Name = "entry16";
			this.entry16.IsEditable = true;
			this.entry16.InvisibleChar = '●';
			this.table7.Add (this.entry16);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table7 [this.entry16]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.filechooserbutton3 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton3.Name = "filechooserbutton3";
			this.table7.Add (this.filechooserbutton3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table7 [this.filechooserbutton3]));
			w7.TopAttach = ((uint)(5));
			w7.BottomAttach = ((uint)(6));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.table7.Add (this.label15);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table7 [this.label15]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("label14");
			this.table7.Add (this.label16);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table7 [this.label16]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("label13");
			this.table7.Add (this.label17);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table7 [this.label17]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("label12");
			this.table7.Add (this.label18);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table7 [this.label18]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("label11");
			this.table7.Add (this.label19);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table7 [this.label19]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
			this.table7.Add (this.label20);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table7 [this.label20]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table7);
			this.frame6.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel1;
			this.vbox4.Add (this.frame6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame6]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button8);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button8]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button7]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button6]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button5]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add (this.treeview2);
			this.GtkAlignment1.Add (this.GtkScrolledWindow);
			this.frame8.Add (this.GtkAlignment1);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel6;
			this.vbox4.Add (this.frame8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame8]));
			w25.Position = 3;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 439;
			this.DefaultHeight = 454;
			this.Show ();
		}
	}
}
